version: '3.8'
services:
  api:
    build: .
    container_name: back
    restart: always  
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules